export const SET_TENANTS = 'SET_TENANTS';
export const ADD_TENANT = 'ADD_TENANT';
export const UPDATE_TENANT = 'UPDATE_TENANT';


export const SET_BILL_TYPES = 'SET_BILL_TYPES';
export const ADD_BILL_TYPE = 'ADD_BILL_TYPE';
export const DELETE_BILL_TYPE = "DELETE_BILL_TYPE";
export const ADD_BILL = "ADD_BILL";
export const DELETE_BILL = "DELETE_BILL";

export const TOGGLE_ADD_BILL_DIALOG = 'TOGGLE_ADD_BILL_DIALOG';
export const SET_CURRENT_BILL_TYPE = 'SET_CURRENT_BILL_TYPE';